#!/usr/bin/env bash

cd $OPENSHIFT_HOMEDIR/app-root/runtime/repo

# Update .htpasswd location
sed -i "s|AuthUserFile /vagrant/.htpasswd|AuthUserFile $OPENSHIFT_HOMEDIR/app-root/data/.htpasswd|g" .htaccess  

# Download phpliteadmin
wget https://phpliteadmin.googlecode.com/files/phpliteAdmin_v1-9-5.zip
unzip phpliteAdmin_v1-9-5.zip

# Create links
ln -s ../data/configuration.php .
ln -s ../data/phpliteadmin.config.php .
ln -s ../data/errors.log .
ln -s ../data/groph-singleparent.sqlite .

# Installing dependencies
../data/composer.phar install