#!/usr/bin/env bash
cd $OPENSHIFT_HOMEDIR/app-root/runtime/repo
# Create links
ln -s ../data/configuration.php .
ln -s ../data/errors.log .
ln -s ../data/groph-singleparent.sqlite .
../data/composer.phar install
